server:
  port: 8079

spring:
  application:
    name: springcloud-gateway
  cloud:
  ##网关配置
    gateway:
      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。
      #默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
      discovery:
        #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
        locator:
          enabled: true
      routes:
      - id: api-provider1
      ##lb表示向注册中心拿服务名
        uri: lb://provider-service
        predicates:
        ##
        - Path=/whale/**
      - id: api-provider2
      ##lb表示向注册中心拿服务名
        uri: lb://provider-service
        predicates:
        ##
        - Path=/cnctsys/**
        filters:
        - PrefixPath=/whale
      - id: api-consumer
        uri: lb://consumer-service
        predicates:
        - Path=/cloudconsumer/**
        #- Path=/**
#        filters:
#        - PrefixPath=/cloudconsumer
      - id: gateway-test
        uri: http://www.baidu.com
        predicates:
        - Path=/baidu


#eureka
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8076/eureka/

##fegn 调用熔断配置
feign:
  hystrix:
    enabled: true
